
/* This file was generated automatically by Zephir do not modify it! */

#ifndef ZEPHIR_CLASS_ENTRIES_H
#define ZEPHIR_CLASS_ENTRIES_H

#include "paxb/binding/annotations/abstractloader.zep.h"
#include "paxb/binding/annotations/annotation.zep.h"
#include "paxb/binding/annotations/exception.zep.h"
#include "paxb/binding/annotations/filter/annotationinterface.zep.h"
#include "paxb/binding/annotations/loaderinterface.zep.h"
#include "paxb/binding/annotations/xml/annotationinterface.zep.h"
#include "paxb/binding/metadata/container.zep.h"
#include "paxb/binding/metadata/exception.zep.h"
#include "paxb/binding/metadata/factory.zep.h"
#include "paxb/binding/metadata/factoryinterface.zep.h"
#include "paxb/binding/metadata/metadata.zep.h"
#include "paxb/binding/metadata/metadatainterface.zep.h"
#include "paxb/binding/structure/abstractstructure.zep.h"
#include "paxb/binding/structure/structureinterface.zep.h"
#include "paxb/filter/exception/filterexception.zep.h"
#include "paxb/filter/exception/invalidcallbackexception.zep.h"
#include "paxb/filter/exception/invalidoptionsexception.zep.h"
#include "paxb/filter/exception/invalidzendfilterexception.zep.h"
#include "paxb/filter/exception/missingoptionsexception.zep.h"
#include "paxb/filter/exception/ruledefinitionexception.zep.h"
#include "paxb/filter/exception/ruleoptionsexception.zep.h"
#include "paxb/filter/filter.zep.h"
#include "paxb/filter/filterinterface.zep.h"
#include "paxb/filter/filters/alpha.zep.h"
#include "paxb/filter/filters/alphanumeric.zep.h"
#include "paxb/filter/filters/digits.zep.h"
#include "paxb/filter/filters/filterinterface.zep.h"
#include "paxb/filter/filters/htmlentities.zep.h"
#include "paxb/filter/filters/integer.zep.h"
#include "paxb/filter/filters/objectawarefilter.zep.h"
#include "paxb/filter/filters/pregreplace.zep.h"
#include "paxb/filter/filters/regexp.zep.h"
#include "paxb/filter/filters/stripnewlines.zep.h"
#include "paxb/filter/filters/striptags.zep.h"
#include "paxb/filter/filters/tolower.zep.h"
#include "paxb/filter/filters/trim.zep.h"
#include "paxb/filter/filters/zend.zep.h"
#include "paxb/filter/loader.zep.h"
#include "paxb/filter/loaderinterface.zep.h"
#include "paxb/filter/objectwalker.zep.h"
#include "paxb/xml/binding/structure/attribute.zep.h"
#include "paxb/xml/binding/structure/element.zep.h"

#endif